# Generated by Django 5.2.14 on 2026-05-24 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postsharelink_feedback_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_reply_t_d4d885_idx',
            old_name='blog_commen_reply_t_acb85f_idx',
        ),
        migrations.RenameIndex(
            model_name='commentfeedback',
            new_name='blog_commen_comment_c7b55d_idx',
            old_name='blog_commen_comment_9fbbd2_idx',
        ),
        migrations.RenameIndex(
            model_name='commentfeedback',
            new_name='blog_commen_user_id_a41485_idx',
            old_name='blog_commen_user_id_9a181a_idx',
        ),
        migrations.RenameIndex(
            model_name='postfeedback',
            new_name='blog_postfe_post_id_b283ad_idx',
            old_name='blog_postfe_post_id_8b991d_idx',
        ),
        migrations.RenameIndex(
            model_name='postfeedback',
            new_name='blog_postfe_user_id_e88390_idx',
            old_name='blog_postfe_user_id_2693ca_idx',
        ),
        migrations.RenameIndex(
            model_name='postsharelink',
            new_name='blog_postsh_token_82950b_idx',
            old_name='blog_postsh_token_3de2e4_idx',
        ),
        migrations.RenameIndex(
            model_name='postsharelink',
            new_name='blog_postsh_post_id_a522c5_idx',
            old_name='blog_postsh_post_id_136132_idx',
        ),
        migrations.AlterField(
            model_name='commentfeedback',
            name='value',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='value',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
