# Generated by Django 5.2.14 on 2026-05-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postdraft_and_migrate_legacy_drafts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postdraft',
            new_name='blog_postdr_updated_9f8201_idx',
            old_name='blog_postdr_updated_31c7c5_idx',
        ),
        migrations.RenameIndex(
            model_name='postdraft',
            new_name='blog_postdr_author__eb9703_idx',
            old_name='blog_postdr_author__774f43_idx',
        ),
        migrations.RenameIndex(
            model_name='postdraft',
            new_name='blog_postdr_slug_d8c325_idx',
            old_name='blog_postdr_slug_759c4e_idx',
        ),
    ]
