# Generated by Django 5.2.14 on 2026-05-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_conditional_access_assets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentviewlog',
            new_name='blog_conten_content_518c3b_idx',
            old_name='blog_conten_content_0386da_idx',
        ),
        migrations.RenameIndex(
            model_name='contentviewlog',
            new_name='blog_conten_content_98d632_idx',
            old_name='blog_conten_content_938775_idx',
        ),
        migrations.RenameIndex(
            model_name='contentviewlog',
            new_name='blog_conten_user_id_724790_idx',
            old_name='blog_conten_user_id_9d0553_idx',
        ),
        migrations.RenameIndex(
            model_name='contentviewlog',
            new_name='blog_conten_ip_addr_1ffff3_idx',
            old_name='blog_conten_ip_addr_bbb905_idx',
        ),
        migrations.RenameIndex(
            model_name='contentviewlog',
            new_name='blog_conten_session_75e160_idx',
            old_name='blog_conten_session_7b3302_idx',
        ),
    ]
