# Generated by Django 5.2.14 on 2026-05-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_sitesetting_vip_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_non_admin_create_post',
            field=models.BooleanField(default=False),
        ),
    ]
