# Generated by Django 5.2.14 on 2026-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_add_allow_non_admin_create_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='non_admin_max_post_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vip_only_create_post',
            field=models.BooleanField(default=False),
        ),
    ]
