# Generated by Django 5.2.14 on 2026-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_add_non_admin_post_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_non_admin_create_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='non_admin_max_book_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vip_only_create_book',
            field=models.BooleanField(default=False),
        ),
    ]
