# Generated by Django 5.2.14 on 2026-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_sitesetting_allow_non_admin_create_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vip_only_comment',
            field=models.BooleanField(default=False),
        ),
    ]
