# Generated by Django 5.2.14 on 2026-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_sitesetting_allow_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='code_expire_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='code_resend_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_register',
            field=models.BooleanField(default=False),
        ),
    ]
