# Generated by Django 5.2.14 on 2026-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_sitesetting_register_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_scope',
            field=models.CharField(choices=[('unified', 'Unified'), ('standalone', 'Standalone')], default='unified', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='vip_access_permission',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('conditional', 'Conditional')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='vip_condition_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='access_scope',
            field=models.CharField(choices=[('unified', 'Unified'), ('standalone', 'Standalone')], default='unified', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='vip_access_permission',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('conditional', 'Conditional')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='vip_condition_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('post_create', 'Create post'), ('post_update', 'Update post'), ('post_delete', 'Delete post'), ('comment_create', 'Create comment'), ('comment_update', 'Update comment'), ('comment_delete', 'Delete comment'), ('profile_update', 'Update profile'), ('user_create', 'Create user'), ('user_update', 'Update user'), ('user_delete', 'Delete user'), ('user_asset_update', 'Update user assets')], max_length=32),
        ),
    ]
