# Generated by Django 5.2.14 on 2026-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_book_access_scope_book_vip_access_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdraft',
            name='access_scope',
            field=models.CharField(choices=[('unified', 'Unified'), ('standalone', 'Standalone')], default='unified', max_length=16),
        ),
        migrations.AddField(
            model_name='postdraft',
            name='vip_access_permission',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('conditional', 'Conditional')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='postdraft',
            name='vip_condition_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
