# Generated by Django 5.2.14 on 2026-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_add_password_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_reprint',
            field=models.BooleanField(default=False),
        ),
    ]
