# Generated by Django 5.2.14 on 2026-06-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_attachment_and_site_setting_size'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='blog_attach_uploade_d29d3b_idx',
            old_name='blog_attach_uploade_bbf6a1_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='blog_attach_visibil_d45f16_idx',
            old_name='blog_attach_visibil_7a8db2_idx',
        ),
        migrations.RenameIndex(
            model_name='attachmentpasswordrecord',
            new_name='blog_attach_user_id_f5f870_idx',
            old_name='blog_attachm_user_id_f8c7eb_idx',
        ),
        migrations.RenameIndex(
            model_name='attachmentpurchaserecord',
            new_name='blog_attach_user_id_0db0bf_idx',
            old_name='blog_attachp_user_id_66d196_idx',
        ),
        migrations.RenameIndex(
            model_name='attachmentpurchaserecord',
            new_name='blog_attach_attachm_bbfcbe_idx',
            old_name='blog_attachp_attachm_d31ccd_idx',
        ),
        migrations.RenameIndex(
            model_name='bookstar',
            new_name='blog_bookst_book_id_88b680_idx',
            old_name='blog_bookstar_book_created_idx',
        ),
        migrations.RenameIndex(
            model_name='bookstar',
            new_name='blog_bookst_user_id_ec31d4_idx',
            old_name='blog_bookstar_user_created_idx',
        ),
    ]
