# Generated by Django 5.2.14 on 2026-06-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_sitesetting_author_reward_ratios_authorrewardrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authorrewardrecord',
            new_name='blog_author_reader__c170c1_idx',
            old_name='blog_author_reader__4c55f5_idx',
        ),
        migrations.RenameIndex(
            model_name='authorrewardrecord',
            new_name='blog_author_author__563fc1_idx',
            old_name='blog_author_author__ccb59b_idx',
        ),
    ]
