# Generated by Django 5.2.14 on 2026-06-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_usermoneyhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commentrewardrecord',
            new_name='blog_commen_user_id_5768bb_idx',
            old_name='blog_comment_user_id_5cdbfa_idx',
        ),
        migrations.RenameIndex(
            model_name='commentrewardrecord',
            new_name='blog_commen_post_id_ffb498_idx',
            old_name='blog_comment_post_id_f11192_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoneyhistory',
            new_name='blog_usermo_user_id_57b617_idx',
            old_name='blog_usermo_user_id_347fd3_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoneyhistory',
            new_name='blog_usermo_reason__30d717_idx',
            old_name='blog_usermo_reason__96012b_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoneyhistory',
            new_name='blog_usermo_related_d0a107_idx',
            old_name='blog_usermo_related_e6e20b_idx',
        ),
    ]
