# Generated by Django 5.2.14 on 2026-06-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_user_media_paths'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpointshistory',
            new_name='blog_userpo_user_id_3e1dac_idx',
            old_name='blog_userpo_user_id_117e13_idx',
        ),
        migrations.RenameIndex(
            model_name='userpointshistory',
            new_name='blog_userpo_reason__9073ba_idx',
            old_name='blog_userpo_reason__0c55ec_idx',
        ),
        migrations.RenameIndex(
            model_name='userpointshistory',
            new_name='blog_userpo_related_255593_idx',
            old_name='blog_userpo_related_9a80fe_idx',
        ),
    ]
