# Generated by Django 5.2.14 on 2026-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_github_userprofile_qq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_email_on_namecard',
            field=models.BooleanField(default=False),
        ),
    ]
