from django.urls import path

from apps.blog.views.post import (
    ArticleListView,
    BlogDetailView,
    ManagePostCoverDeleteView,
    ManagePostCreateView,
    ManagePostDeleteView,
    ManagePostDraftCoverDeleteView,
    ManagePostDraftDeleteView,
    ManagePostDraftPreviewView,
    ManagePostDraftUpdateView,
    ManagePostImportView,
    ManagePostListView,
    ManagePostMarkdownImportView,
    ManagePostReferenceSearchView,
    ManagePostRevisionStartView,
    ManagePostShareLinkDeleteView,
    ManagePostShareLinkUpdateView,
    ManagePostUpdateView,
    MarkdownPreviewView,
    PostFeedbackToggleView,
    PostLinkPreviewView,
    PostShareDetailView,
    PostShareLinkCreateView,
    SearchView,
)

urlpatterns = [
    path("articles/", ArticleListView.as_view(), name="article-list"),
    path("blog/markdown-preview/", MarkdownPreviewView.as_view(), name="blog-markdown-preview"),
    path("blog/link-preview/", PostLinkPreviewView.as_view(), name="blog-post-preview"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog-detail"),
    path("blog/<slug:slug>/share-links/", PostShareLinkCreateView.as_view(), name="blog-share-create"),
    path("blog/<slug:slug>/feedback/", PostFeedbackToggleView.as_view(), name="blog-feedback-toggle"),
    path("share/<str:token>/", PostShareDetailView.as_view(), name="blog-share-detail"),
    path("search/", SearchView.as_view(), name="blog-search"),
    path("manage/posts/", ManagePostListView.as_view(), name="manage-posts"),
    path("manage/posts/new/", ManagePostCreateView.as_view(), name="manage-post-create"),
    path("manage/posts/import/", ManagePostImportView.as_view(), name="manage-post-import"),
    path("manage/posts/import-markdown/", ManagePostMarkdownImportView.as_view(), name="manage-post-import-markdown"),
    path("manage/posts/reference-search/", ManagePostReferenceSearchView.as_view(), name="manage-post-reference-search"),
    path("manage/posts/<int:pk>/edit/", ManagePostUpdateView.as_view(), name="manage-post-update"),
    path("manage/posts/<int:pk>/revision/start/", ManagePostRevisionStartView.as_view(), name="manage-post-revision-start"),
    path("manage/posts/<int:pk>/cover/delete/", ManagePostCoverDeleteView.as_view(), name="manage-post-cover-delete"),
    path("manage/posts/<int:pk>/delete/", ManagePostDeleteView.as_view(), name="manage-post-delete"),
    path("manage/drafts/<int:pk>/edit/", ManagePostDraftUpdateView.as_view(), name="manage-post-draft-update"),
    path("manage/drafts/<int:pk>/preview/", ManagePostDraftPreviewView.as_view(), name="manage-post-draft-preview"),
    path("manage/drafts/<int:pk>/cover/delete/", ManagePostDraftCoverDeleteView.as_view(), name="manage-post-draft-cover-delete"),
    path("manage/drafts/<int:pk>/delete/", ManagePostDraftDeleteView.as_view(), name="manage-post-draft-delete"),
    path("manage/share-links/<int:pk>/edit/", ManagePostShareLinkUpdateView.as_view(), name="manage-share-link-update"),
    path("manage/share-links/<int:pk>/delete/", ManagePostShareLinkDeleteView.as_view(), name="manage-share-link-delete"),
]
