ACCESS_STATUS_GRANTED = "granted"
ACCESS_STATUS_PURCHASE_REQUIRED = "purchase_required"
ACCESS_STATUS_INSUFFICIENT_MONEY = "insufficient_money"
ACCESS_STATUS_INSUFFICIENT_POINTS = "insufficient_points"
ACCESS_STATUS_INVALID_CONDITION = "invalid_condition"

__all__ = [
    "ACCESS_STATUS_GRANTED",
    "ACCESS_STATUS_PURCHASE_REQUIRED",
    "ACCESS_STATUS_INSUFFICIENT_MONEY",
    "ACCESS_STATUS_INSUFFICIENT_POINTS",
    "ACCESS_STATUS_INVALID_CONDITION",
]
